CREATE DATABASE COLLAGE; -- CREATE DATABASE
USE COLLAGE; -- USE A PARTICULAR DATABASE
CREATE TABLE STUDENTS(
id INT PRIMARY KEY,
NAME VARCHAR (50),
AGE INT NOT NULL
);

INSERT INTO STUDENTS VALUES(1,"AMAN",20);
INSERT INTO STUDENTS VALUES(2,"ARYAN",20);

SELECT * FROM STUDENTS; -- select all database

SHOW TABLES;  
SHOW DATABASES;

USE COLLAGE;

CREATE TABLE TEAMS(
rollno INT default 1  PRIMARY KEY,
name VARCHAR(50)
);

INSERT INTO TEAMS (rollno, name) VALUES (101, 'VARUN');
INSERT INTO TEAMS ( rollno, name) VALUES (201, 'PIYUSH');
INSERT INTO TEAMS ( rollno, name) VALUES ( 0, 'harsh');

SELECT * FROM TEAMS;